[snippets]
custom_paths = []
include_default_snippets = true

[experimental]

[save]
autosave_delay = 1000
format_on_save = false
autosave = "off"

[completion]
copilot = false
activate_on_typing = true

[formatting]
line_length = 79

[ai]
rules = ""

[language_servers.pylsp]
enable_pyflakes = false
enable_pydocstyle = false
enable_flake8 = false
enable_ruff = true
enable_pylint = false
enable_mypy = true
enabled = true

[runtime]
watcher_on_save = "lazy"
output_max_bytes = 8000000
auto_instantiate = true
auto_reload = "off"
reactive_tests = true
default_sql_output = "auto"
std_stream_max_bytes = 1000000
on_cell_change = "autorun"

[package_management]
manager = "pip"

[keymap]
preset = "default"

[keymap.overrides]

[server]
browser = "default"
follow_symlink = false

[display]
theme = "light"
default_table_page_size = 10
default_width = "medium"
code_editor_font_size = 14
dataframes = "rich"
cell_output = "above"
